# Develop override settings

url: http://localhost:4000
repository               : "academicpages/academicpages.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
